Check for "exit status 1" in "docker pull" output and if true, inform the user and exit shell script. (In order to still get the "docker pull" output while waiting for the rosvita download, the "docker pull" command is doubled, now. But the second "docker pull" should not take too long, since the image is already there...)

diff --git a/rosvita/downloads/get_rosvita b/rosvita/downloads/get_rosvita
--- a/rosvita/downloads/get_rosvita
+++ b/rosvita/downloads/get_rosvita
@@ -41,8 +41,14 @@ echo "The ROSVITA image will be downloaded from Docker Hub, press CTRL+C to canc
 read -p "Press ENTER to continue"
 echo "Getting ROSVITA from Docker Hub.."
 sudo docker pull xamla/rosvita:latest
+if [[ $(sudo docker pull xamla/rosvita:latest | grep -c 'exit status 1') > 0 ]]; then
+   echo "Could not download latest ROSVITA image. Please check your internet connection and disk space."
+   echo "If the problem does not go away, we are happy to help you at http://discuss.xamla.com."
+   exit 1
+fi
 if [[ $(sudo docker images | grep -c 'xamla/rosvita') == 0 ]]; then
-   echo "Could not download ROSVITA image. Please check your internet connection. If the problem does not go away, we are happy to help you at http://discuss.xamla.com."
+   echo "Could not download ROSVITA image. Please check your internet connection and disk space." 
+   echo "If the problem does not go away, we are happy to help you at http://discuss.xamla.com."
    exit 1
 else
    echo "ROSVITA image has been downloaded successfully."
